// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {}
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",                                                                   // Your API version
	Host:             "localhost:4040",                                                        // The host where your API will be accessible
	BasePath:         "/",                                                                     // The base path for your API
	Schemes:          []string{"http"},                                                        // The protocols (http or https)
	Title:            "Receipt Processor API",                                                 // Title of your API
	Description:      "This API allows users to process receipts and retrieve reward points.", // A description of what the API does
	InfoInstanceName: "swagger",                                                               // Instance name, should be unique (default is fine)
	SwaggerTemplate:  docTemplate,                                                             // Reference to the template defined above
	LeftDelim:        "{{",                                                                    // Delimiters used for templating
	RightDelim:       "}}",                                                                    // Delimiters used for templating
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
